module.exports = {
  BAD_REQUEST_ERROR_CODE: 400,
  UNAUTHORIZED_ERROR_CODE: 401,
  FORBIDDEN_ERROR_CODE: 403,
  NOT_FOUND_ERROR_CODE: 404,
  CONFLICT_ERROR_CODE: 409,
  INTERNAL_SERVER_ERROR_CODE: 500,
};
